### ISSUE TITLE
Unable to create executor due to ch.cern.DemoMetricsPlugin

### ISSUE THREAD

**Issue by SvenGuthe** [cerndb/SparkPlugins#3]
I have tried to use the Plugin in our local kubernetes-kind-cluster.

I have added the following settings to the spark configurations:

```
"spark.jars.packages": "ch.cern.sparkmeasure:spark-plugins_2.12:0.1"
"spark.hadoop.fs.hdfs.impl": "org.apache.hadoop.hdfs.DistributedFileSystem"
"spark.hadoop.fs.file.impl": "org.apache.hadoop.fs.LocalFileSystem"
"spark.plugins": "ch.cern.DemoMetricsPlugin"
```

... and some Graphite Settings. When I try to run the Configuration I ended in a non descriptive failure message:

`2022-05-22 09:28:43,388 ERROR o.a.s.s.TaskSchedulerImpl [dispatcher-CoarseGrainedScheduler] Lost executor 8 on 10.244.1.109: Unable to create executor due to ch.cern.DemoMetricsPlugin`

Even with Spark Log Level Debug there is no hint to solve it.

**Comment by LucaCanali** [comment]
Hi, thanks for reporting this.
Can you please add additional information on your confiration and environment. In particular, Spark version you are using.
Best,
Luca

**Comment by SvenGuthe** [comment]
Hi Luca,
currently I am using Spark 3.1.2 with the spark-operator (https://github.com/GoogleCloudPlatform/spark-on-k8s-operator). Scala Version 2.12.11. Basis Image: https://console.cloud.google.com/gcr/images/spark-operator/GLOBAL/spark v3.1.1
Best,
Sven

**Comment by LucaCanali** [comment]
Hi Sven,
This works for me using spark-submit (spark-shell). I don't have a system with the spark-operator handy at present.
Could you to reproduce the issue with spark-submit/spark-shell?

**Comment by SvenGuthe** [comment]
Hi Luca,
not really. I tried to use nearly the same configuration in our docker testing environment (instead of the kind kubernetes cluster). But there not even the streaming will start due to HDFS File System issues.
Maybe I could try the configuration on a AWS / Azure Environment via spark-submit later.
